Resources:
    EntriesTable:
        Type: AWS::DynamoDB::Table
        Properties:
            TableName: ${self:custom.tableName}
            AttributeDefinitions:
                - AttributeName: userId
                  AttributeType: S
                - AttributeName: entryId
                  AttributeType: S
            KeySchema:
                - AttributeName: userId
                  KeyType: HASH
                - AttributeName: entryId
                  KeyType: RANGE
            # Set the capacity to auto-scale
            ProvisionedThroughput:
                ReadCapacityUnits: 5
                WriteCapacityUnits: 5
