Resources:
    EntriesTable:
        Type: AWS::DynamoDB::Table
        Properties:
            TableName: ${self:custom.entriesTableName}
            AttributeDefinitions:
                - AttributeName: userId
                  AttributeType: S
                - AttributeName: entryId
                  AttributeType: S
            KeySchema:
                - AttributeName: userId
                  KeyType: HASH
                - AttributeName: entryId
                  KeyType: RANGE
            # Set the capacity to auto-scale
            ProvisionedThroughput:
                ReadCapacityUnits: 3
                WriteCapacityUnits: 3
    PhotoKeyMappingsTable:
        Type: AWS::DynamoDB::Table
        Properties:
            TableName: ${self:custom.photoKeyMappingsTableName}
            AttributeDefinitions:
                - AttributeName: photoKey
                  AttributeType: S
            KeySchema:
                - AttributeName: photoKey
                  KeyType: HASH
            # Set the capacity to auto-scale
            ProvisionedThroughput:
                ReadCapacityUnits: 3
                WriteCapacityUnits: 3
